//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\ODataParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ODataParserParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IODataParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.odataUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOdataUri([NotNull] ODataParserParser.OdataUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.serviceRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceRoot([NotNull] ODataParserParser.ServiceRootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.odataRelativeUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOdataRelativeUri([NotNull] ODataParserParser.OdataRelativeUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.resourcePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourcePath([NotNull] ODataParserParser.ResourcePathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.collectionNavigation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionNavigation([NotNull] ODataParserParser.CollectionNavigationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.keyPredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyPredicate([NotNull] ODataParserParser.KeyPredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.simpleKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleKey([NotNull] ODataParserParser.SimpleKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.compoundKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundKey([NotNull] ODataParserParser.CompoundKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.keyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyValuePair([NotNull] ODataParserParser.KeyValuePairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.keyPropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyPropertyValue([NotNull] ODataParserParser.KeyPropertyValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.singleNavigation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleNavigation([NotNull] ODataParserParser.SingleNavigationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.collectionPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionPath([NotNull] ODataParserParser.CollectionPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.singlePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinglePath([NotNull] ODataParserParser.SinglePathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexPath([NotNull] ODataParserParser.ComplexPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.count"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCount([NotNull] ODataParserParser.CountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.links"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinks([NotNull] ODataParserParser.LinksContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] ODataParserParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundOperation([NotNull] ODataParserParser.BoundOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.actionImportCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionImportCall([NotNull] ODataParserParser.ActionImportCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundActionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundActionCall([NotNull] ODataParserParser.BoundActionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundEntityFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundEntityFuncCall([NotNull] ODataParserParser.BoundEntityFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundEntityColFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundEntityColFuncCall([NotNull] ODataParserParser.BoundEntityColFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundComplexFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundComplexFuncCall([NotNull] ODataParserParser.BoundComplexFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundComplexColFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundComplexColFuncCall([NotNull] ODataParserParser.BoundComplexColFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundPrimitiveFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundPrimitiveFuncCall([NotNull] ODataParserParser.BoundPrimitiveFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundPrimitiveColFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundPrimitiveColFuncCall([NotNull] ODataParserParser.BoundPrimitiveColFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityFunctionImportCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityFunctionImportCall([NotNull] ODataParserParser.EntityFunctionImportCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityColFunctionImportCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityColFunctionImportCall([NotNull] ODataParserParser.EntityColFunctionImportCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexFunctionImportCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexFunctionImportCall([NotNull] ODataParserParser.ComplexFunctionImportCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexColFunctionImportCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexColFunctionImportCall([NotNull] ODataParserParser.ComplexColFunctionImportCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveFunctionImportCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveFunctionImportCall([NotNull] ODataParserParser.PrimitiveFunctionImportCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveColFunctionImportCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveColFunctionImportCall([NotNull] ODataParserParser.PrimitiveColFunctionImportCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.functionParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameters([NotNull] ODataParserParser.FunctionParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameter([NotNull] ODataParserParser.FunctionParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.functionParameterName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameterName([NotNull] ODataParserParser.FunctionParameterNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.parameterAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterAlias([NotNull] ODataParserParser.ParameterAliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.containerQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContainerQualifier([NotNull] ODataParserParser.ContainerQualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.queryOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueryOptions([NotNull] ODataParserParser.QueryOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.queryOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueryOption([NotNull] ODataParserParser.QueryOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.systemQueryOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystemQueryOption([NotNull] ODataParserParser.SystemQueryOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregate([NotNull] ODataParserParser.AggregateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aggregateCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateCommand([NotNull] ODataParserParser.AggregateCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aggregateClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateClause([NotNull] ODataParserParser.AggregateClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aggregateList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateList([NotNull] ODataParserParser.AggregateListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aggregateItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateItem([NotNull] ODataParserParser.AggregateItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.groupbyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupbyList([NotNull] ODataParserParser.GroupbyListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.groupbyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupbyItem([NotNull] ODataParserParser.GroupbyItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.dynamicProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamicProperty([NotNull] ODataParserParser.DynamicPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aggregateFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateFunction([NotNull] ODataParserParser.AggregateFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.expand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpand([NotNull] ODataParserParser.ExpandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.expandItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpandItem([NotNull] ODataParserParser.ExpandItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.expandOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpandOption([NotNull] ODataParserParser.ExpandOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.levels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLevels([NotNull] ODataParserParser.LevelsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter([NotNull] ODataParserParser.FilterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.orderby"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderby([NotNull] ODataParserParser.OrderbyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.orderbyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderbyItem([NotNull] ODataParserParser.OrderbyItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.skip"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkip([NotNull] ODataParserParser.SkipContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.top"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop([NotNull] ODataParserParser.TopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.format"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormat([NotNull] ODataParserParser.FormatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.inlinecount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlinecount([NotNull] ODataParserParser.InlinecountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect([NotNull] ODataParserParser.SelectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.selectItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectItem([NotNull] ODataParserParser.SelectItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.allOperationsInSchema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllOperationsInSchema([NotNull] ODataParserParser.AllOperationsInSchemaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.qualifiedActionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedActionName([NotNull] ODataParserParser.QualifiedActionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.qualifiedFunctionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedFunctionName([NotNull] ODataParserParser.QualifiedFunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.parameterTypeNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterTypeNames([NotNull] ODataParserParser.ParameterTypeNamesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.parameterTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterTypeName([NotNull] ODataParserParser.ParameterTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.skiptoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkiptoken([NotNull] ODataParserParser.SkiptokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aliasAndValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAliasAndValue([NotNull] ODataParserParser.AliasAndValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.parameterNameAndValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterNameAndValue([NotNull] ODataParserParser.ParameterNameAndValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.parameterValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterValue([NotNull] ODataParserParser.ParameterValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityReference([NotNull] ODataParserParser.EntityReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.customQueryOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomQueryOption([NotNull] ODataParserParser.CustomQueryOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.customName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomName([NotNull] ODataParserParser.CustomNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.customValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomValue([NotNull] ODataParserParser.CustomValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.commonExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommonExpr([NotNull] ODataParserParser.CommonExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boolCommonExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolCommonExpr([NotNull] ODataParserParser.BoolCommonExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.firstMemberExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFirstMemberExpr([NotNull] ODataParserParser.FirstMemberExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.memberExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberExpr([NotNull] ODataParserParser.MemberExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.lambdaPredicatePrefixExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaPredicatePrefixExpr([NotNull] ODataParserParser.LambdaPredicatePrefixExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.inscopeVariableExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInscopeVariableExpr([NotNull] ODataParserParser.InscopeVariableExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.implicitVariableExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitVariableExpr([NotNull] ODataParserParser.ImplicitVariableExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.lambdaVariableExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaVariableExpr([NotNull] ODataParserParser.LambdaVariableExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.collectionNavigationExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionNavigationExpr([NotNull] ODataParserParser.CollectionNavigationExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.singleNavigationExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleNavigationExpr([NotNull] ODataParserParser.SingleNavigationExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.collectionPathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionPathExpr([NotNull] ODataParserParser.CollectionPathExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexPathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexPathExpr([NotNull] ODataParserParser.ComplexPathExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.singlePathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinglePathExpr([NotNull] ODataParserParser.SinglePathExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boundFunctionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundFunctionExpr([NotNull] ODataParserParser.BoundFunctionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.functionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionExpr([NotNull] ODataParserParser.FunctionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.functionExprParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionExprParameters([NotNull] ODataParserParser.FunctionExprParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.functionExprParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionExprParameter([NotNull] ODataParserParser.FunctionExprParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.anyExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnyExpr([NotNull] ODataParserParser.AnyExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.allExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllExpr([NotNull] ODataParserParser.AllExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.lambdaPredicateExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaPredicateExpr([NotNull] ODataParserParser.LambdaPredicateExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.methodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallExpr([NotNull] ODataParserParser.MethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boolMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolMethodCallExpr([NotNull] ODataParserParser.BoolMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.substringOfMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubstringOfMethodCallExpr([NotNull] ODataParserParser.SubstringOfMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.startsWithMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartsWithMethodCallExpr([NotNull] ODataParserParser.StartsWithMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.endsWithMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndsWithMethodCallExpr([NotNull] ODataParserParser.EndsWithMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.lengthMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLengthMethodCallExpr([NotNull] ODataParserParser.LengthMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.indexOfMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexOfMethodCallExpr([NotNull] ODataParserParser.IndexOfMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.substringMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubstringMethodCallExpr([NotNull] ODataParserParser.SubstringMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.toLowerMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToLowerMethodCallExpr([NotNull] ODataParserParser.ToLowerMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.toUpperMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToUpperMethodCallExpr([NotNull] ODataParserParser.ToUpperMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.trimMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrimMethodCallExpr([NotNull] ODataParserParser.TrimMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.concatMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatMethodCallExpr([NotNull] ODataParserParser.ConcatMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.yearMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYearMethodCallExpr([NotNull] ODataParserParser.YearMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.monthMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthMethodCallExpr([NotNull] ODataParserParser.MonthMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.dayMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayMethodCallExpr([NotNull] ODataParserParser.DayMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.daysMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDaysMethodCallExpr([NotNull] ODataParserParser.DaysMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.hourMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHourMethodCallExpr([NotNull] ODataParserParser.HourMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.hoursMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHoursMethodCallExpr([NotNull] ODataParserParser.HoursMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.minuteMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinuteMethodCallExpr([NotNull] ODataParserParser.MinuteMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.minutesMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinutesMethodCallExpr([NotNull] ODataParserParser.MinutesMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.secondMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondMethodCallExpr([NotNull] ODataParserParser.SecondMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.secondsMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondsMethodCallExpr([NotNull] ODataParserParser.SecondsMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.timeMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeMethodCallExpr([NotNull] ODataParserParser.TimeMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.dateMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateMethodCallExpr([NotNull] ODataParserParser.DateMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.roundMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoundMethodCallExpr([NotNull] ODataParserParser.RoundMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.floorMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloorMethodCallExpr([NotNull] ODataParserParser.FloorMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.ceilingMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCeilingMethodCallExpr([NotNull] ODataParserParser.CeilingMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.getTotalOffsetMinutesExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetTotalOffsetMinutesExpr([NotNull] ODataParserParser.GetTotalOffsetMinutesExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.distanceMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDistanceMethodCallExpr([NotNull] ODataParserParser.DistanceMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geoLengthMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeoLengthMethodCallExpr([NotNull] ODataParserParser.GeoLengthMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.intersectsMethodCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntersectsMethodCallExpr([NotNull] ODataParserParser.IntersectsMethodCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.minDateTimeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinDateTimeExpr([NotNull] ODataParserParser.MinDateTimeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.maxDateTimeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaxDateTimeExpr([NotNull] ODataParserParser.MaxDateTimeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.nowDateTimeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNowDateTimeExpr([NotNull] ODataParserParser.NowDateTimeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boolParenExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolParenExpr([NotNull] ODataParserParser.BoolParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.parenExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] ODataParserParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] ODataParserParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] ODataParserParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.eqExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqExpr([NotNull] ODataParserParser.EqExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.neExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNeExpr([NotNull] ODataParserParser.NeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.ltExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLtExpr([NotNull] ODataParserParser.LtExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.leExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeExpr([NotNull] ODataParserParser.LeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.gtExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGtExpr([NotNull] ODataParserParser.GtExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeExpr([NotNull] ODataParserParser.GeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.hasExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHasExpr([NotNull] ODataParserParser.HasExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpr([NotNull] ODataParserParser.AddExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.subExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubExpr([NotNull] ODataParserParser.SubExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulExpr([NotNull] ODataParserParser.MulExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.divExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivExpr([NotNull] ODataParserParser.DivExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModExpr([NotNull] ODataParserParser.ModExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.negateExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegateExpr([NotNull] ODataParserParser.NegateExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] ODataParserParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.isofExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsofExpr([NotNull] ODataParserParser.IsofExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.castExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpr([NotNull] ODataParserParser.CastExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexColInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexColInUri([NotNull] ODataParserParser.ComplexColInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexInUri([NotNull] ODataParserParser.ComplexInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.collectionPropertyInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionPropertyInUri([NotNull] ODataParserParser.CollectionPropertyInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveColInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveColInUri([NotNull] ODataParserParser.PrimitiveColInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexPropertyInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexPropertyInUri([NotNull] ODataParserParser.ComplexPropertyInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexTypeMetadataInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexTypeMetadataInUri([NotNull] ODataParserParser.ComplexTypeMetadataInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.typeNVPInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeNVPInUri([NotNull] ODataParserParser.TypeNVPInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitivePropertyInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitivePropertyInUri([NotNull] ODataParserParser.PrimitivePropertyInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityRefColInUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityRefColInUri([NotNull] ODataParserParser.EntityRefColInUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityRefInJSON"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityRefInJSON([NotNull] ODataParserParser.EntityRefInJSONContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveLiteralInJSON"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveLiteralInJSON([NotNull] ODataParserParser.PrimitiveLiteralInJSONContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.stringInJSON"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringInJSON([NotNull] ODataParserParser.StringInJSONContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.charInJSON"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharInJSON([NotNull] ODataParserParser.CharInJSONContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.escape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEscape([NotNull] ODataParserParser.EscapeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.numberInJSON"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberInJSON([NotNull] ODataParserParser.NumberInJSONContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.intPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntPart([NotNull] ODataParserParser.IntPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fracPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFracPart([NotNull] ODataParserParser.FracPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.expPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpPart([NotNull] ODataParserParser.ExpPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.actionRequestBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionRequestBody([NotNull] ODataParserParser.ActionRequestBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.actionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionParameter([NotNull] ODataParserParser.ActionParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.actionParameterName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionParameterName([NotNull] ODataParserParser.ActionParameterNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.actionParameterValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionParameterValue([NotNull] ODataParserParser.ActionParameterValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.qualifiedTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedTypeName([NotNull] ODataParserParser.QualifiedTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.qualifiedEntityTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedEntityTypeName([NotNull] ODataParserParser.QualifiedEntityTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.qualifiedComplexTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedComplexTypeName([NotNull] ODataParserParser.QualifiedComplexTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.qualifiedEnumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedEnumerationTypeName([NotNull] ODataParserParser.QualifiedEnumerationTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] ODataParserParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.namespacePart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespacePart([NotNull] ODataParserParser.NamespacePartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entitySetName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntitySetName([NotNull] ODataParserParser.EntitySetNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.namedEntity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedEntity([NotNull] ODataParserParser.NamedEntityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityTypeName([NotNull] ODataParserParser.EntityTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexTypeName([NotNull] ODataParserParser.ComplexTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.enumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationTypeName([NotNull] ODataParserParser.EnumerationTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.enumerationMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationMember([NotNull] ODataParserParser.EnumerationMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.odataIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOdataIdentifier([NotNull] ODataParserParser.OdataIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.identifierLeadingCharacter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierLeadingCharacter([NotNull] ODataParserParser.IdentifierLeadingCharacterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.identifierCharacter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierCharacter([NotNull] ODataParserParser.IdentifierCharacterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty([NotNull] ODataParserParser.PropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveProperty([NotNull] ODataParserParser.PrimitivePropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveKeyProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveKeyProperty([NotNull] ODataParserParser.PrimitiveKeyPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveNonKeyProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveNonKeyProperty([NotNull] ODataParserParser.PrimitiveNonKeyPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveColProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveColProperty([NotNull] ODataParserParser.PrimitiveColPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexProperty([NotNull] ODataParserParser.ComplexPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexColProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexColProperty([NotNull] ODataParserParser.ComplexColPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.streamProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStreamProperty([NotNull] ODataParserParser.StreamPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.navigationProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNavigationProperty([NotNull] ODataParserParser.NavigationPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityNavigationProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityNavigationProperty([NotNull] ODataParserParser.EntityNavigationPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityColNavigationProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityColNavigationProperty([NotNull] ODataParserParser.EntityColNavigationPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityContainer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityContainer([NotNull] ODataParserParser.EntityContainerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] ODataParserParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.actionImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionImport([NotNull] ODataParserParser.ActionImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] ODataParserParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityFunction([NotNull] ODataParserParser.EntityFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityColFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityColFunction([NotNull] ODataParserParser.EntityColFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexFunction([NotNull] ODataParserParser.ComplexFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexColFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexColFunction([NotNull] ODataParserParser.ComplexColFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveFunction([NotNull] ODataParserParser.PrimitiveFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveColFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveColFunction([NotNull] ODataParserParser.PrimitiveColFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityFunctionImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityFunctionImport([NotNull] ODataParserParser.EntityFunctionImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.entityColFunctionImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityColFunctionImport([NotNull] ODataParserParser.EntityColFunctionImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexFunctionImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexFunctionImport([NotNull] ODataParserParser.ComplexFunctionImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.complexColFunctionImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexColFunctionImport([NotNull] ODataParserParser.ComplexColFunctionImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveFunctionImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveFunctionImport([NotNull] ODataParserParser.PrimitiveFunctionImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveColFunctionImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveColFunctionImport([NotNull] ODataParserParser.PrimitiveColFunctionImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveLiteral([NotNull] ODataParserParser.PrimitiveLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.null_symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_symbol([NotNull] ODataParserParser.Null_symbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary([NotNull] ODataParserParser.BinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.boolean_symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_symbol([NotNull] ODataParserParser.Boolean_symbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimal([NotNull] ODataParserParser.DecimalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.decimalBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalBody([NotNull] ODataParserParser.DecimalBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.double_symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble_symbol([NotNull] ODataParserParser.Double_symbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.doubleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleBody([NotNull] ODataParserParser.DoubleBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle([NotNull] ODataParserParser.SingleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.singleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleBody([NotNull] ODataParserParser.SingleBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.nanInfinity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNanInfinity([NotNull] ODataParserParser.NanInfinityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.guid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuid([NotNull] ODataParserParser.GuidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.guidBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuidBody([NotNull] ODataParserParser.GuidBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.byte_symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitByte_symbol([NotNull] ODataParserParser.Byte_symbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.sbyte"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSbyte([NotNull] ODataParserParser.SbyteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.int16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt16([NotNull] ODataParserParser.Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.int32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt32([NotNull] ODataParserParser.Int32Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt64([NotNull] ODataParserParser.Int64Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.int64Body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt64Body([NotNull] ODataParserParser.Int64BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.aString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAString([NotNull] ODataParserParser.AStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.pCharNoSingleQuote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPCharNoSingleQuote([NotNull] ODataParserParser.PCharNoSingleQuoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] ODataParserParser.DateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.dateBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateBody([NotNull] ODataParserParser.DateBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.dateTimeOffset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateTimeOffset([NotNull] ODataParserParser.DateTimeOffsetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.dateTimeOffsetBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateTimeOffsetBody([NotNull] ODataParserParser.DateTimeOffsetBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDuration([NotNull] ODataParserParser.DurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.durationBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDurationBody([NotNull] ODataParserParser.DurationBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.timeOfDay"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfDay([NotNull] ODataParserParser.TimeOfDayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.timeOfDayBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfDayBody([NotNull] ODataParserParser.TimeOfDayBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.year"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYear([NotNull] ODataParserParser.YearContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.month"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonth([NotNull] ODataParserParser.MonthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.day"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDay([NotNull] ODataParserParser.DayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.hour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHour([NotNull] ODataParserParser.HourContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.minute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinute([NotNull] ODataParserParser.MinuteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.second"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecond([NotNull] ODataParserParser.SecondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fractionalSeconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFractionalSeconds([NotNull] ODataParserParser.FractionalSecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.enum_symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_symbol([NotNull] ODataParserParser.Enum_symbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] ODataParserParser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValue([NotNull] ODataParserParser.EnumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyCollection([NotNull] ODataParserParser.GeographyCollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fullCollectionLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullCollectionLiteral([NotNull] ODataParserParser.FullCollectionLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.collectionLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionLiteral([NotNull] ODataParserParser.CollectionLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geoLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeoLiteral([NotNull] ODataParserParser.GeoLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyLineString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyLineString([NotNull] ODataParserParser.GeographyLineStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fullLineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullLineStringLiteral([NotNull] ODataParserParser.FullLineStringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.lineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineStringLiteral([NotNull] ODataParserParser.LineStringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.lineStringData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineStringData([NotNull] ODataParserParser.LineStringDataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyMultiLineString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyMultiLineString([NotNull] ODataParserParser.GeographyMultiLineStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fullMultiLineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullMultiLineStringLiteral([NotNull] ODataParserParser.FullMultiLineStringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.multiLineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiLineStringLiteral([NotNull] ODataParserParser.MultiLineStringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyMultiPoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyMultiPoint([NotNull] ODataParserParser.GeographyMultiPointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fullMultiPointLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullMultiPointLiteral([NotNull] ODataParserParser.FullMultiPointLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.multiPointLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiPointLiteral([NotNull] ODataParserParser.MultiPointLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyMultiPolygon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyMultiPolygon([NotNull] ODataParserParser.GeographyMultiPolygonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fullMultiPolygonLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullMultiPolygonLiteral([NotNull] ODataParserParser.FullMultiPolygonLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.multiPolygonLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiPolygonLiteral([NotNull] ODataParserParser.MultiPolygonLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyPoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyPoint([NotNull] ODataParserParser.GeographyPointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fullPointLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullPointLiteral([NotNull] ODataParserParser.FullPointLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.sridLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSridLiteral([NotNull] ODataParserParser.SridLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.pointLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointLiteral([NotNull] ODataParserParser.PointLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.pointData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointData([NotNull] ODataParserParser.PointDataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.positionLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPositionLiteral([NotNull] ODataParserParser.PositionLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyPolygon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyPolygon([NotNull] ODataParserParser.GeographyPolygonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.fullPolygonLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullPolygonLiteral([NotNull] ODataParserParser.FullPolygonLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.polygonLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPolygonLiteral([NotNull] ODataParserParser.PolygonLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.polygonData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPolygonData([NotNull] ODataParserParser.PolygonDataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.ringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRingLiteral([NotNull] ODataParserParser.RingLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryCollection([NotNull] ODataParserParser.GeometryCollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryLineString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryLineString([NotNull] ODataParserParser.GeometryLineStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryMultiLineString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryMultiLineString([NotNull] ODataParserParser.GeometryMultiLineStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryMultiPoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryMultiPoint([NotNull] ODataParserParser.GeometryMultiPointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryMultiPolygon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryMultiPolygon([NotNull] ODataParserParser.GeometryMultiPolygonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryPoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryPoint([NotNull] ODataParserParser.GeometryPointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryPolygon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryPolygon([NotNull] ODataParserParser.GeometryPolygonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geographyPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeographyPrefix([NotNull] ODataParserParser.GeographyPrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.geometryPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeometryPrefix([NotNull] ODataParserParser.GeometryPrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.host"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHost([NotNull] ODataParserParser.HostContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.port"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort([NotNull] ODataParserParser.PortContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.regName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegName([NotNull] ODataParserParser.RegNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.segmentNZ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegmentNZ([NotNull] ODataParserParser.SegmentNZContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ODataParserParser.pChar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPChar([NotNull] ODataParserParser.PCharContext context);
}
